version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
    commands:
      - echo Installing source NPM dependencies `date`
      - node --version
      - npm install -g pnpm
      - pnpm --version
      - pnpm install
    pre_build:
      commands:
        - echo Building the source on `date`
    build:
      commands:
        - echo Build started on `date`
        - pnpm run build
        - echo "Build completed on `date`"
    post_build:
      commands:
        - echo Build completed on `date`
        - aws s3 cp $CODEBUILD_SRC_DIR/dist $DEPLOY_TARGET_S3_URI --recursive
        - aws cloudfront create-invalidation --distribution-id $DEPLOY_CLOUDFRONT_DIST_ID --paths '/index.html'
