version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
    commands:
      - echo "Installing source NPM dependencies"
      - npm install -g pnpm
      - pnpm install
    pre_build:
      commands:
        - echo Building the source on `data`
    build:
      commands:
        - echo Build started on `date`
        - pnpm run build
        - echo "Build completed on `date`"
    post_build:
      commands:
        - echo "Build completed on `date`"
        - aws s3 cp build/ s3://$S3_BUCKET_NAME/ --recursive

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.pnpm-store/**/*'
